### ISSUE TITLE
Where should I edit?

### ISSUE THREAD

**Issue by RyosukeTakahashi** [bryan--p/stripe-apps-script#1]
Thank you for the great script !
Exactly what i was looking for.
However, I'm having some trouble using your code.
I have copied your code and made 2 files(gs.gs and HTML.html) to my google apps script project and edited the public key.
Deployed it as a web app and clicked the purchase button and the form appears.
Entered the "4242 4242 4242 4242" test number and other information.

<img width="416" alt="2015-10-28 23 46 16" src="https://cloud.githubusercontent.com/assets/12992519/10792030/588835b6-7dce-11e5-90c5-51ea58aaa6cd.png">

Then clicked Pay 30000 yen button. The Pay 30000 button changes the color and it seems as though the payment has succeeded.

However, if I check my stripe dashboard there is no payment and no added customer. I am sure that I am in the test mode in my dashboard,.

The only code I changed is the "YOUR PUBLIC KEY" and some part like currency and amount.
Is there anything else I should edit?

And this is another question. How do I save the card detail only (for charging it later) ?

**Comment by bryan--p** [comment]
[#L63](https://github.com/bryan--p/stripe-apps-script/blob/master/GS.gs#L63) assumes that you've set your own "textSecret" in the scriptProperties 

As for saving details to charge later you'll have to review Stripes Docs for that and follow up with their support if needed
